[[github_account]]
token = ""
username = "excloo"

[[resource_sync]]
name = "komodo"

[resource_sync.config]
branch = "main"
delete = true
git_account = "excloo"
repo = "excloo/komodo"
resource_path = ["."]
webhook_enabled = true
