{
	"data": "ENC[AES256_GCM,data:tIYTYzsit+MB7eu9m5nUM99Ia+g2yrHC6dLki7MrbU2jZglCJtOQd0yYaCg7cz0puCFuW2D3+C5OGPM/a9Zyyzu7L76k5Wszmulz8J16lGXPLPYhB1/sKGVGIbAvjaxGbGXiulN5KpY3VOAz7WcnQ2gpl/4En/qi07IzeSwxVYyxQhufEMxvgUyGklAsaznnsDNFr+MrmHRZBmOhOKKLb1fefgoaHhNV/wLGiJz4HM/lYmr7xaL6d6YeQybiJ9k7HmUeiTXyUVW8R5n4EWFJF0vI63UXtUQ14fk03uVTUieM5NKjuQvvFnmsQnycXPav+DKDfeE0wXrS/SwAkHeMTHgAYlw+XbnTcgypuJ9QrwRBxFrzv3ZOO+vAIgH/Xf8=,iv:aaGtdgUJLNUUaaY3dsw0Khw3IUbwx63Z4QGkXWmjbCk=,tag:VJPT5pC5MfblLzIe5LiaLw==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneHUxMzJ2QVNwT1NhaVND\naHJwbWtvY2xsbm1WQnkrMzJOY3lsYjFaNVFFCkRjYTd3ZXZkOHFwb1BLZ09STlNS\nRkxOWUlEalRmdEduZFRBMkdtbVBDcE0KLS0tIDgrQ3RLcU5RNU1BckovaDAxRGZs\nVFlBZ1hQdjNzRjV4VFJtMmZLemF1alEKmbyRoXAiEI8x+iEnGKbknpGeDvU9liQs\nyBh4V6o+yTP8wJM78r0/9WdqAaCztMTDVr9Cibbxt59FjXQ2L6qGmQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-06-16T23:11:48Z",
		"mac": "ENC[AES256_GCM,data:7j1/TjhRZ053ECjZVCUPcwBJLkHkIF0Eg0jLMyKiCYkzFb+XLk7vgjo45GxD8eO4rwi06CxveD1hVi7fl1AlTgoZJn3wwHmPpLs/t1DpnebxZOWq5GWMm/ZEI5yAUkOsIiHV0cYUXW1vbhtYhieCI1oWwr874XH00qQiO0VMejY=,iv:fMF1l3qCl/7viM9yTqkxxIZrRxYWG0VIE9hBKReRz+M=,tag:lUEKd2bhTfcR3XB2AfOYsA==,type:str]",
		"version": "3.13.1"
	}
}
