{
	"data": "ENC[AES256_GCM,data:Ce551p9JUzaq5cH4uKGPi94IbPYtzKL3BR0RiL4Xa/RfZQREN+xH0yG8mMvH47UQVfTOeHsP5quE3VN/WhjnEr9nFGnArIPIfqBFarfEcgDtmWw75iIehy2UeJBtjMXyW4E6Y0LcBOETkdKj8jjOAsSLmVS+l1QhKvaPubpe3eYnMAiFM4RPKb2aabRp4pJixf3S5P1wdu5xWnKQtqZWZ8LQm0jNBIRxwDF1IIXws9ZuKaP5AgG+Yfd2qA/t3yy37z3KdkKymd7M87JAn/oBuMdQH4trUjypTwzUWsfxP7Cw+J6QvDKdGnHLGJfoumWjtEfJX5cRBUuv1omn0SHtr3qMlJb2hHA4l2v6cbPHVwJgH+PZyGWjzUSTRSqotKZDHnFqN8eJ2L4O7niPinruIjAQZ29T0OPUIo8/s6cN7jpPPuI/CA==,iv:p+b7X+wwX+/kmLvr4Sljt4COTi5ZRcANvYyQquT1iHQ=,tag:krgsNoYF8JG44f+u/i0ylg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeDdVMnI3dkxVTDR0c3kw\nNS9yUFc5Sm9WWjNnd0oxbTE0bHY1eE9nNkRVCm1jbkhQZGxlWXlVamcrbGs5TlJO\nQWhFNFJWVG1xd3NFVzRTZVY2L1BMWDQKLS0tIGJlbDluTXhBSW9LZjF0aXFuYXVp\nMFdnQWdQY0hjanB1TXNTNU1JVzhQcUkKD2eoEHzxK4EXGfi856HudQZlrpM6YnZ6\nREejtARXXwhKaNm82wixPUDvFvcMQWwpHlqbLfBAIi0n3aN6LvvhvQ==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1efn67qrhcfhdjycg0sckmnpytcm765ndwys0zfg8dth2lqqss93qk8tsjd"
			}
		],
		"lastmodified": "2026-06-16T23:11:48Z",
		"mac": "ENC[AES256_GCM,data:jyZKqrJ8K610W4JhZjwxBaHNrPqBEba1VvyPyL5+tWnaayJ8l22Ontd2U1V/mT4JE08YJ6+6Drzd2xp65vl9UGZl+StqqSohrifSsaKqlSTRkz4RRzoWaeTD2iC3NRfMdH3VW3aQXLGSbfzPKM+iL5jTO+3ioIDHdXtuLxMc97M=,iv:CnQzUKZYw+S7Ye7XGQW3O4cLkgXMOo/KLmewWB8LihU=,tag:WwSr2qdzmj/sngqWES6rDQ==,type:str]",
		"version": "3.13.1"
	}
}
