services:
    periphery:
        environment:
            PERIPHERY_PASSKEY: ENC[AES256_GCM,data:35NyAb6NTCz/1nFDxOrA5I7KC4jUom0T/9Vy6IZt7vk=,iv:AFNLiyfb0y5/i0AVkyGwWJwXgBVvVIoe5/g8UVWNQqo=,tag:Hji7r5NeFjfJfD5xDdsMfg==,type:str]
            SOPS_AGE_KEY: ENC[AES256_GCM,data:bWZcElcetCM63Du6ucGg2cql1nqzW0/AWrM0HDwvjZB1RpoMbqhb3VRlo6uJlGBItki4hy5xZgpQ35ntcWZEJgkkBNlZfoCzIEU=,iv:0RO7pHNsclrlAPUg1IFp17/thjiD8UR02wpnhRugkok=,tag:1eg8w5ZyYsQabqj2OAY/Hw==,type:str]
        image: ENC[AES256_GCM,data:WtIrVyMujG+aSws3L35Azpq+Xd8mAE/ANx3oSoqmE6IIqUO7+dpg,iv:PdZnbUdbLvQrdCiTobxh7sdFoV0w2Z4+ENp84fCUu94=,tag:uTmhe61lfzeeh4ZaBdejXQ==,type:str]
        network_mode: ENC[AES256_GCM,data:0422bQ==,iv:qhMDPA3yTG2WrCZ2pSYAQcJKYoxhpLNNH6eD/90fC1I=,tag:hj7wf9094e2OW9136EZ9sA==,type:str]
        restart: ENC[AES256_GCM,data:RhWQkIS1Vap2otWfC/o=,iv:wm6ZziFXacDeOSNI22Yp0rpGsm60dg8YbnJE5QuHsIA=,tag:u8rgej4loQ07ndOswmaGlg==,type:str]
        volumes:
            - ENC[AES256_GCM,data:HhOkws8QRYe8hyQdCHxXHv16j1CZdAoNjmqitZGFXjyZrWcVpMK0Hko=,iv:I9NMOPo7iisokHB1WyYbUw5SMJF38ge/kzhBFGhX/Bs=,tag:0cX9408Ddellm79i4kUFoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSlJjamk1SmNRTzZPWEhG
            aFdDcXlTRTBPZmxKSEFhOWhLc0hNYnRlQ0IwCjJaK0w3SGRwWE5GVWhhTlIrSTh6
            QU42QjNlYmcyTDdTZVhGampEbWNZdFEKLS0tIDJ2OTRpR29KeFNHQ3ZVeksrSTY2
            cHBpVFpORmVUNUNMa2JsYWEwNFl5K28KxaLhXUNcM2uDTA4r097DNcyF+tr14xsc
            8+8cNQ19pfc89iu88m4vsGRh3bQ4aW8b2LMfYvCEnVXWji3TmcxP3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
    lastmodified: "2026-06-12T04:59:35Z"
    mac: ENC[AES256_GCM,data:jLs9vthS8lrYQ6uYcS1XTYylyIQIDAi8e6tWsfpwgJpnZ6HMFZ0gutv6ioTYfIGYo9+OiQpdDRTI7jx2tSTsljb7nsKhexFa14hHXqP51+44U0nEME0gwxPItH9NU2DCUReUil1dhwITzaU0Q2cP9fgDH49a1a0MXQTuA3BMuJk=,iv:ZtRccEaBWrw1dKdM9TSrQ9W82K6DMPmlInq17jp2Jqw=,tag:0IDyhIMdoqvwe4LBWMzBqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
