services:
    periphery:
        environment:
            PERIPHERY_PASSKEY: ENC[AES256_GCM,data:HdNeY2l3KXDFTApBTzzWgstAjwQGF4byb+560MttXiE=,iv:iky8CXlvuybnXtbRw9fDea9re8H6cpUE87RMS04khlY=,tag:8Nu8ib7kFaXpfXjv2es5Og==,type:str]
            SOPS_AGE_KEY: ENC[AES256_GCM,data:GhpToDl75yKwh4HvAJalV4QeRd4jZQ6ft/N8fLryvYkELY01bprcsCQJTF0FwssmdIaqHDp7UfnEHpj0zkAitPRv1pAAf7KMVIQ=,iv:9wLlI4IfN5+OEnAr++v1zrOQg44+cbcWOX146871rYo=,tag:TA+sbhw4MhpMbUTPUpbzvQ==,type:str]
        image: ENC[AES256_GCM,data:GHqHtZnrrL/VXjWqhzxDzi2I8TkBDKFPT/O9yHlLH0EQcy+4wZ+s,iv:CmLBmosQNSF5oww+8nrZfQGWYzz7VKSY7qSQHW5mwpk=,tag:YYu+U5jt+SgnCqaqRYwW/g==,type:str]
        network_mode: ENC[AES256_GCM,data:e1pssQ==,iv:8IueUbKc/7fE0OL0NLXAS/zZ/0sOVDagGVU6bvJV1ME=,tag:W12ILUu1kA9KGgf1IoLX/Q==,type:str]
        restart: ENC[AES256_GCM,data:kKwBy1Dpadu7iNlaOkc=,iv:EKKoaSZgY4NfmOXATKqfT3YoFv2/feSSWixZTM6Dpyo=,tag:F+V9wceMhxDWJMThFGhH8A==,type:str]
        volumes:
            - ENC[AES256_GCM,data:cS0r7YFXCgjLuRuWmEwib9bt+oLXDfR4HJPWUXutdsFM933pelfWfpo=,iv:vsVkwuoQ6fnFstsUwXhmoX1n0hafIrdyyfPPMDOOUBc=,tag:WzB0wKtkkuSoOWGEbKg/jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R0FTMC9lVTgydkNzSHdz
            TEVVTFFzdlYrdTZHdE5zd1VPYkhUSjRqb3hZCjVJMk05SDJnZy9xRlZCaUNlQzNN
            UkNLcHZNOGVuUGZsemJWenpjMUxlYUUKLS0tIDVJMTNYbkpNUTJtU3lBbXM1VWN3
            UTZ2NG8vV0hUb3BHdk9RVitLdnpwNzQK17RNncPzNtZtqAOgGgkWk/RH76f8dZ90
            nWtx5nojoyZfR9jGSoLWFohMGuTIpJQGQymB5NN4KHabRuRZjcmKaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
    lastmodified: "2026-06-11T12:22:17Z"
    mac: ENC[AES256_GCM,data:3fEebJCzSsRAi1RgsRFD/USA266lTdSqDft0ObEBTMVfuBbmbl6WavzXI9JwtYJg7KqT86HRhlNbiW3YShnlztLWQf8bPmTU5AntZbXb+7CwnpQxCtcS5oi4MfUayDmpKQ2h4nmLkHa8qQUPmR90jriy4eg87ZvCE7D7V87pYC4=,iv:RFDyo1v0Q/lSUPJA3RmYgNBrIa+M+IEk5glETTc6z/E=,tag:Ww3R/nBXpiiAk0YOkIZekQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
