services:
    beszel-agent:
        environment:
            HUB_URL: ENC[AES256_GCM,data:8KSPoZkP+CrU7StytkogLMJ4Ql6o1uKB8w64mX3pJG41hFya,iv:PyfAh09IzR1m+FIn0r/lPCebjNvusussjDd++NlJMRc=,tag:FmnuCAvGL0UXj60fQl9lJg==,type:str]
            KEY: ENC[AES256_GCM,data:T5ZZfCtHNYkvVGBqBK07Fe98MHiDmg3MttCVGBKuOTnwhs1mFpKSPIEpfivjudUkYJS9LhPiNvkFsVG+LonvLvs0nT1St4Fwo4/nVX8apjU=,iv:H3bTcyBqdEzoc5skIt+LYKMy9Aj2bwUFLgRQbfohyqk=,tag:UDSmHxJmbjl3MBexcxVIWg==,type:str]
            LISTEN: ENC[AES256_GCM,data:hef29KE=,iv:nF2fiyzT3tilHps2suMEtNZR53abUY2TPTTuTwq+gq8=,tag:dztGR+KJQXW20/rlzwg4lA==,type:int]
            TOKEN: ENC[AES256_GCM,data:lYdmxBPuz839IK6gME5WWG5sRL3L+zVFlKHEHfBO/uoFmdYC,iv:sh4QVy9niwI0CJ2olyK+N4vQhUE2wSchVA8eEgKjLkw=,tag:TRAaDc88VRW+PAzDPoh5mg==,type:str]
        image: ENC[AES256_GCM,data:aFYZukXDNxiJJz8X6bVr+P/mJsnWTtX73AJJ,iv:k0OvsVQ9Ho84W2mLPCX1w5H+uoIuSerYGYMtvg36z6Q=,tag:yWgmwfqtvi++kmUZ56xxvA==,type:str]
        network_mode: ENC[AES256_GCM,data:NOHMuw==,iv:9W+yPCk+Oy2RKowBhXruJeEL1dh/W/7lJb6ODNSqEbk=,tag:LQeIkKesPtRQa5EECrVF2w==,type:str]
        restart: ENC[AES256_GCM,data:FBi839kacIAIgq/ngwg=,iv:OxiaVgsmmnQEFm/kKVGDP1A+w7BeSsqdySeOv0YxVh4=,tag:B5k6jhXrNftZNJj/8pKSWQ==,type:str]
        volumes:
            - ENC[AES256_GCM,data:7lbFoW+Us/A+aO0hK9J8X7DHkWYOHTcsikYFkZTVj7hJ2fS3rbgg1t7dCOJnpytn4OLc+YSKxeZdEU/weA5dKVwD,iv:ht3a2oG3Vws39XAQ+7Qo4tzgLNm3fFYGjKPQ8tJzpGM=,tag:b8QNo84X5Ex5CnUH1ru8JQ==,type:str]
            - ENC[AES256_GCM,data:+QLM5ZSNrX5PZEVoPnXTy08EtEUpvfraonAZ+vdG34vb1v78s17PTWHrK5I=,iv:ovXE1e4ENNpvYIYlY8VXJ1T0bPCUUrlnsdbuUxozXAc=,tag:8tU80Nzzx9bxLDCPr+s9xQ==,type:str]
            - ENC[AES256_GCM,data:I7DlTHM5DmXsCYep+82xpJVTgeDvIDU/v3I=,iv:5E6Wd+n2u+5164sy1BSRKjGOxQgsouynZNdedvWaX7U=,tag:c4k+TdmdYJQoyfh20ZGRqw==,type:str]
volumes:
    data: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OTdYN1kxZWczQ1pPVFh6
            TGtteGJaTjEwdWUvWU1XNnFVSEZsb3ZYQ2pRCkx2eWRmbDhxR3VIWEYrL0FUbzl4
            VmNkd3p4OFNjdHZMQWZGeTg5ODJEL1UKLS0tIGJ1MS9YU0FnU3NiNndwS2RKOWRR
            bE43WkVqREduQkFsUVNZb1FpL1BZL2sK3LLiVtc9jKtoMiyZXeBRSq95pMd+dS47
            2ZAPAhqLGOrLS58zYc7y0m75MUdwiRItYxHl/KzStCe0yUbNG6b1Vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1heqmzgcj5d2fe7c96leq9kqm6vc4mqhpn94d685q3px9utzlq98q2tv268
    lastmodified: "2026-06-12T04:59:35Z"
    mac: ENC[AES256_GCM,data:XwHsa1718p/0NrkooZQuqC23UaiMcFALrxXyRUfa9Waa3r8ag5gRbI2kLAdMILx0rmLpj7NSC7m0xqhiRHN/BAw8ufBAV9QHlNqhYuzDzScTLwRfYI82BAIt36MEqtm3czeqH+JM/bpfAVRl7lH+DyFDekqymx3lfZNuY4XsESw=,iv:/L0G9M8Q1U2V2eJ2ydcgN0lghmU3kHXY0VfCnXE1e8k=,tag:8i+Lm2An8gM06SHySDefPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
